Add more cortex queries
TheHive-Project/TheHive4py pull request #371
Opened 2024-11-26 14:28 UTC by Anko59

2024-11-26 18:11 UTC, Kamforka commented
I'll take a closer look but on the high level it seems fine!
Maybe one thing that is not ideal is the simple return types. 
Probably we can define some more advanced type hints for those?

2024-11-26 21:09 UTC, Kamforka requested changes

2024-11-26 21:09 UTC, Kamforka commented on thehive4py/endpoints/cortex.py
> +    def list_analyzers(self) -> dict:
So it looks like we miss a query parameter `range` based on the [api docs](https://docs.strangebee.com/thehive/api-docs/#tag/Cortex/operation/List%20Analyzers)

Additionally I'd also refine the output type hint as according to the docs it should be a list of analyzers.

For that please define the module `thehive4py/types/cortex.py` and add something like: 

```python
# thehive4py/types/cortex.py
from typing import List, TypedDict


class OutputAnalyzertRequired(TypedDict):
    id: str
    name: str
    version: str
    description: str


class OutputAnalyzer(OutputAnalyzerRequired, total=False):
    dataTypeList: List[str]
    cortexIds: List[str]
```


```suggestion
    def list_analyzers(self, range: str) -> List[OutputAnalyzer]:
```

2024-11-26 21:09 UTC, Kamforka commented on thehive4py/endpoints/cortex.py
> +    def list_analyzers_by_type(self, data_type: str) -> dict:
Based on the above findings and suggestion please revisit all these methods too and align them with the docs if they are not aligned already.

2024-11-27 15:47 UTC, Anko59 commented
Thanks for the review,

I applied the changes that you suggested. I added cortex types for the objects returned by the API and added the range parameter to the list_analyzers function. I did not find any other missing parameter.

I used python 3.9+ typing (`dict` and `list` instead of `Dict` and `List`). It was already like this in the cortex.py, though I noticed most of the repo still uses pre 3.9 typing.

To better match the documentation, "responder action" and "analyzer job" could be renamed "cortex action" and "cortex job", but I think the first ones are easier to understand.

2024-11-28 17:57 UTC, Kamforka requested changes

2024-11-28 17:57 UTC, Kamforka commented on thehive4py/types/cortex.py
> +# thehive4py/types/cortex.py
remove this comment please, I just added it in the example as clarity :)

2024-11-28 17:57 UTC, Kamforka commented on thehive4py/endpoints/cortex.py
>          self, object_id: str, object_type: str, responder_id: str
When checking the corresponding [docs](https://docs.strangebee.com/thehive/api-docs/#tag/Cortex/operation/Create%20an%20action) I can see that it supports more parameters for this endpoint, what about adding an input type hint too? E.g.:

```python
class InputResponderActionRequired(TypedDict):
    responderId: str
    objectType: str
    objectId: str

<...>
```

and then:

```suggestion
        self, action: InputResponderAction
```

2024-11-28 17:57 UTC, Kamforka commented on thehive4py/endpoints/cortex.py
>          self, cortex_id: str, analyzer_id: str, observable_id: str
same suggestion as for the responder action one

2024-11-28 17:57 UTC, Kamforka commented on thehive4py/endpoints/cortex.py
> +        )
As I see in the [docs](https://docs.strangebee.com/thehive/api-docs/#tag/Cortex/operation/List%20Analyzers) `range` should be a query parameter, e.g.:

```suggestion
        params = {"range": range}
        return self._session.make_request(
            "GET", path="/api/connector/cortex/analyzer", params=params
        )
```

And as far as I remember you don't really need the if-else check in this case as when a query parameter is `None` the `requests` library will just ignore it.

2024-11-28 17:57 UTC, Kamforka commented on thehive4py/endpoints/cortex.py
> +    def get_analyzer(self, object_id: str) -> OutputAnalyzer:
typo:
```suggestion
    def get_analyzer(self, analyzer_id: str) -> OutputAnalyzer:
```

2024-11-28 18:03 UTC, Kamforka commented
> I applied the changes that you suggested. I added cortex types for the objects returned by the API and added the range parameter to the list_analyzers function. I did not find any other missing parameter.

Nice, great job so far!

> I used python 3.9+ typing (`dict` and `list` instead of `Dict` and `List`). It was already like this in the cortex.py, though I noticed most of the repo still uses pre 3.9 typing.

Unfortunately we still support 3.8, so can you please fall back to `typing.List` and `typing.Dict` where necessary? I plan to drop support 2025Q1.

> To better match the documentation, "responder action" and "analyzer job" could be renamed "cortex action" and "cortex job", but I think the first ones are easier to understand.

I agree with the naming convention, more to the point than cortex action and job!

My last point to this PR would be the missing integration tests. Unfortunately we don't have a Cortex instance configured yet, so we cannot test all the endpoints, but probably we can add some dummy test for the `list_analyzers` and `list_responders` methods, would you like to give it a try?

2024-12-02 15:56 UTC, Kamforka requested changes

2024-12-02 15:56 UTC, Kamforka commented on tests/test_cortex_endpoint.py
> +            assert "id" in analyzer.keys()
Let's keep it even simpler:

```suggestion
        assert analyzers == []
```

2024-12-02 15:56 UTC, Kamforka commented on tests/test_cortex_endpoint.py
> +            assert "id" in analyzer.keys()
Same goes for this one:
```suggestion
        assert analyzers == []
```

2024-12-02 15:56 UTC, Kamforka commented on tests/test_cortex_endpoint.py
> +            assert _analyzer == analyzer
This is unfortunately not doing anything additional as the `analyzers` list should be empty without a Cortex instance attached, so probably best to remove it for now

2024-12-02 15:56 UTC, Kamforka commented on tests/test_cortex_endpoint.py
> +            assert "id" in responder.keys()
You can also reuse the `test_case` fixture to simplify this:
```suggestion
     def test_list_responders(self, thehive: TheHiveApi, test_case: OutputCase):
        responders = thehive.cortex.list_responders(
            entity_type="case", entity_id=test_case["_id"]
        )
        assert responders == []
```

2024-12-02 15:59 UTC, Kamforka commented
> I implemented the changes you suggested. The tests are really dummy, as there are no responders or analyzers on the test instance, some of the test code is never reached. I don't know how to add responders or analyzers using the API. I will try to document myself.

First of all thank you very much for the changes, great job just as before!!!

To reply to your dummy test concern, unfortunately this is the best we can do at the moment as we don't yet have a live Cortex instance behind the integrator instance of TheHive, so we will always get back empty responder and analyzer lists, but that's okay for now. TheHive cannot create/define analyzers nor responders.

Additionally I added some simplification ideas to your tests, if you implement those I think we are done with this PR.

2024-12-03 17:47 UTC, Kamforka requested changes

2024-12-03 17:47 UTC, Kamforka commented on tests/test_cortex_endpoint.py
> +        assert isinstance(responders, list)
Let's stick to the convention of the tests above:
```suggestion
        assert responders == []
```

2024-12-04 09:49 UTC, Kamforka approved these changes

2024-12-04 20:29 UTC, Kamforka commented
Thank you for your coop, nice one!

2024-12-04 20:29 UTC, merged